.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. huntercoin_qt test_huntercoin_qt
clean: FORCE
	$(MAKE) -C .. huntercoin_qt_clean test_huntercoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_huntercoin_qt_check
huntercoin-qt huntercoin-qt.exe: FORCE
	 $(MAKE) -C .. huntercoin_qt
